[theme]
base="light"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"

[theme]
base="dark"
primaryColor="#FF4B4B"
backgroundColor="#2E2E2E"
textColor="#CFCFCF"
secondaryBackgroundColor="#1C1C1C"

