[theme]
base="light"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"

[theme]
base="dark"
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
textColor="#31333F"
secondaryBackgroundColor="F0F2F6"




